spring.application.name=userservice
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/userservice
spring.datasource.username=serviceuser
spring.jpa.show-sql= true
server.port=8081